<?php

/**
 * @file
 * Pantheon API module and common functions.
 *
 * Currently just one utility and an api.inc.
 */

/**
 * Load the API file.
 */
function pantheon_api_load_api() {
  module_load_include('inc', 'pantheon_api', 'pantheon_api');
}

/**
 * Insure we have curl() for API functions.
 */
function pantheon_api_requirements($phase) {
  if ($phase == 'install' && !function_exists('curl_init')) {
    // Ensure translations don't break at install time
    $t = get_t();
    $requirements['pantheon'] = array(
      'title' => $t('cURL utility'),
      'value' => $t('Not installed'),
      'severity' => REQUIREMENT_ERROR,
      'description' => $t('The CURL library for PHP is missing. Please check the <a href="@url">PHP curl documentation</a> for information on how to correct this.', array('@url' => 'http://www.php.net/manual/en/curl.setup.php')),
    );

    return $requirements;
  }
}
