<?php

/**
 * Implementation of hook_enable()
 */
function pantheon_migrate_enable() {
  drupal_set_message(t('The Pantheon Migrate module has now been enabled. Make sure you have the proper permissions and click !here to begin the migration.', array('!here' => l('here', 'admin/content/backup_migrate/export/pantheon'))));
}

/**
 * Implementation of hook_menu()
 */
function pantheon_migrate_menu() {
  $items['admin/content/backup_migrate/export/pantheon'] = array(
    'title' => 'Pantheon Migrate',
    'description' => 'Migrate the site onto Pantheon',
    'page callback' => 'backup_migrate_menu_callback',
    'page arguments' => array('', 'pantheon_migrate_ui_pantheon_migrate_quick', TRUE),
    'access arguments' => array('access backup and migrate'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implementation of hook_menu_alter()
 */
function pantheon_migrate_menu_alter(&$items) {
  $items['admin/content/backup_migrate/destination/downloadfile']['access callback'] = 'pantheon_migrate_download_access';
  $items['admin/content/backup_migrate/destination/downloadfile']['access arguments'] = array(6, 7);
}

/**
 * Pantheon Token Generation 
 */
function pantheon_migrate_token_get($file_id) {
  $token = md5(session_id() . $file_id . drupal_get_private_key());
  $record = array(
    'file_id' => $file_id,
    'token' => $token,
  );
  drupal_write_record('pantheon_migrate_tokens', $record);
  return $token;
}

/**
 * Pantheon Token Validation
 */
function pantheon_migrate_token_validate($file_id, $token) {
  if ($token_id = db_result(db_query("SELECT token_id FROM {pantheon_migrate_tokens} WHERE file_id = '%s' AND token = '%s'", $file_id, $token))) {
    return TRUE;
  } 
  else {
    return FALSE;
  }
}

/**
 * Access Callback for Download
 */
function pantheon_migrate_download_access($file_id, $token) {
  // Let Users Download as Normal
  if (user_access('access backup files')) {
    return TRUE;
  }

  // Validate Our Special Tokens
  return pantheon_migrate_token_validate($file_id, $token);
}

/**
 * Callback for Pantheon Migration
 */
function pantheon_migrate_ui_pantheon_migrate_quick() {
  $out = "";
  if (user_access('perform backup')) {
    $out .= drupal_get_form('pantheon_migrate_ui_pantheon_migrate_quick_backup_form');
    drupal_set_title(t('Pantheon Migrate'));
  }
  else {
    $out .= t('You do not have permission to back up this site.');
  }
  return $out;
}

/**
 * Implementation of hook_help().
 */
function pantheon_migrate_help($path, $arg) {
  switch($path) {
    case 'admin/content/backup_migrate/export/pantheon':
      return '<p>' . t('Migrate your site to Pantheon by making an archive of your site and then sending it to Pantheon for further setup. For more information, checkout the !readme file.', array('!readme' => l('README.txt', drupal_get_path('module', 'pantheon_migrate') . '/README.txt'))) . '</p>';
      break;
  }
}

/**
 * Pantheon Migrate Form
 */
function pantheon_migrate_ui_pantheon_migrate_quick_backup_form() {
  backup_migrate_include('profiles', 'destinations');

  $form = array();

  $form['quickbackup'] = array(
    '#type' => 'fieldset',
    '#title' => t('Migrate to Pantheon'),
  );

  $form['quickbackup']['data'] = array(
    '#type' => 'markup',
    '#value' => '<p>' . backup_migrate_ui_destination_display_files('pantheonstorage') . '</p>',
  );            

  $form['quickbackup']['source_id'] = array(
    '#type' => 'value',
    '#value' => 'pantheonarchive',
  );

  $form['quickbackup']['destination_id'] = array(
    '#type' => 'value',
    '#value' => 'pantheonstorage',
  );

  $form['quickbackup']['profile_id'] = array(
    '#type' => 'value',
    '#value' => 'pantheonprofile', 
  );

  $form['quickbackup']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create Pantheon Archive'),
    '#weight' => 1,
  );

  $form['#submit'] = array('backup_migrate_ui_manual_quick_backup_form_submit');
  $form['#redirect'] = 'admin/content/backup_migrate/export/pantheon';

  return $form;
}

/**
 * Implementation of hook_backup_migrate_destination_types().
 */
function pantheon_migrate_backup_migrate_destination_types() {
  return array(
    'pantheonarchive' => array(
      'description' => t('Packages the code, database, and files of your site to import into Pantheon.'),
      'file' => drupal_get_path('module', 'pantheon_migrate') .'/pantheon_migrate.backup_migrate.inc',
      'class' => 'backup_migrate_destination_pantheon_migrate',
      'type_name' => t('Pantheon Import'),
      'can_create' => FALSE,
    ),
    'pantheonstorage' => array(
      'file' => drupal_get_path('module', 'pantheon_migrate') .'/pantheon_migrate.backup_migrate.inc',
      'type_name' => t('Pantheon Directory'),
      'class' => 'backup_migrate_destination_files_pantheon_storage',
    ),
  );
}

/**
 * Implementation of hook_backup_migrate_profiles()
 */
function pantheon_migrate_backup_migrate_profiles() {
  $out = array();
  $out['pantheonprofile'] = backup_migrate_crud_create_item('profile', array(
      'name' => t("Pantheon Settings"), 
      'profile_id' => 'pantheonprofile')
  );
  return $out;

}

/**
 * Implementation of hook_backup_migrate_destinations().
 */
function pantheon_migrate_backup_migrate_destinations() {
  $destination = backup_migrate_create_destination('pantheonstorage', array('destination_id' => 'pantheonstorage'));
  return array('pantheonstorage' => $destination);
}
